### ISSUE TITLE
Can't buy other amounts diferent then the total EUR available

### ISSUE THREAD

**Issue by cibernauta78** [nunoloureiro/birdtradebot#5]
By following the rules described we tried to make the bot buy ETH with 50% of EUR amount but it went wrong.

With the rule:
{
            "side": "buy",
            "type": "limit",
            "price": "{inside_bid}",
            "product_id": "ETH-EUR",
            "size": "{max_balance}*0.5"
        }

the bot didnt allow to buy, giving the error attached in the log and went with FALLBACK and bought.

We then tried to use "funds" instead of "size", as we understood from github and GDAX notes

 {
            "side": "buy",
            "type": "limit",
            "price": "{inside_bid}",
            "product_id": "ETH-EUR",
            "funds": "{max_balance}*0.5"
        }

and when we start the bot again we get the error also in the log and the bot crashes.

The question is, how can we buy ETH or BTC with only 50% of the available EUR ?

[bot.log](https://github.com/nunoloureiro/birdtradebot/files/1682933/bot.log)

**Comment by poupas** [comment]
Hi!

Can you show me the rules file used when this error occurred?

```
  File "/home/birdbot/birdtradebot/birdtradebot/rules/birdpersonborg.py", line 18
    'funds': '{max_balance}*0.5'
           ^
SyntaxError: invalid syntax
```

**Comment by cibernauta78** [comment]
[rules_birdpersonborg.zip](https://github.com/nunoloureiro/birdtradebot/files/1686622/rules_birdpersonborg.zip)

Here it is. Thank you.

**Comment by cibernauta78** [comment]
sorry. closed by mistake. open again.

**Comment by poupas** [comment]
Hi,

The scenario described should be achieved with the following configuration:

```python
  {
        'handles': ['BirdpersonBorg'],
        'condition': '"ETHUSD" in {tweet} and "long" in {tweet}.lower()',
        'retries': 2,
        'retry_ttl_s': 200,
        'tweet_ttl_s': 400,
        'market_fallback': True,
        'orders': [
            {
                'side': 'buy',
                'type': 'limit',
                'price': '{inside_bid}',
                'product_id': 'ETH-EUR',
                'size': '{max_balance}*0.5'
            }
        ]
    },
  {
        'handles': ['BirdpersonBorg'],
        'condition': '"BTCEUR" in {tweet} and "long" in {tweet}.lower()',
        'retries': 2,
        'retry_ttl_s': 200,
        'tweet_ttl_s': 400,
        'market_fallback': True,
        'orders': [
            {
                'side': 'buy',
                'type': 'limit',
                'price': '{inside_bid}',
                'product_id': 'BTC-EUR',
                'size': '{max_balance}*0.5'
            }
        ]
    },
```

However, we assume you are trying to use 50% of the EUR balance so that half of the funds go buy ETH and the other half to BTC. If that is the case, it will not work as intended.

 Consider the following scenario:

The initial EUR balance is 100 EUR.

1. The bot receives a signal to buy ETH;
2. The bot buys 50 EUR worth of ETH;

EUR balance is now 50.

3. The bot receives a signal to buy BTC;
4. The bot buys 25 EUR worth of BTC. --> You may have expected it to buy 50 EUR, but since we  multiplied the remaining balance for 0.5, that bot will never be able to use it fully.

We suggest a different approach. The code below will evenly split the EUR balance among purchases.

```python
  {
        'handles': ['BirdpersonBorg'],
        'condition': '"ETHUSD" in {tweet} and "long" in {tweet}.lower()',
        'retries': 2,
        'retry_ttl_s': 200,
        'tweet_ttl_s': 400,
        'market_fallback': True,
        'orders': [
            {
                'side': 'buy',
                'type': 'limit',
                'price': '{inside_bid}',
                'product_id': 'ETH-EUR',
                'size': '{split_balance}'
            }
        ]
    },
  {
        'handles': ['BirdpersonBorg'],
        'condition': '"BTCEUR" in {tweet} and "long" in {tweet}.lower()',
        'retries': 2,
        'retry_ttl_s': 200,
        'tweet_ttl_s': 400,
        'market_fallback': True,
        'orders': [
            {
                'side': 'buy',
                'type': 'limit',
                'price': '{inside_bid}',
                'product_id': 'BTC-EUR',
                'size': '{split_balance}'
            }
        ]
    },
```

**Comment by cibernauta78** [comment]
Hello,
Thank you for the information. The first part its so obvious that I dont know how i didnt see it.

Regarding the option "split_balance", do you have a link to the documentation where it has more information about it? Cant find it in the GDAX API documentation.

Thank you.

**Comment by poupas** [comment]
The `{split_balance}` option was something we developed internally to cater for scenarios like the one you requested :) It does not exist in the GDAX API. When the bot is trying to buy, it will evenly split the balance among all pairs with a short position. Please note that it may still have some bugs.

An example scenario may be helpful.

The initial balance is 100 EUR, 0 BTC, and 0 ETH. I.e., we are short on both BTC and ETH.
The bot is following two pairs: ETH-EUR and BTC-EUR.

1. The bot receives an order to go long on ETH-EUR;
2. The bot calculates how much EUR balance it should use:
  * Total balance = 100 EUR;
  * Pairs that are currently short:  ETH-EUR and BTC-EUR = 2;
  * EUR balance to purchase ETH: 100 EUR / 2 = 50 EUR;
3. The bot purchases 50 EUR worth of ETH;

Current balance: 50 EUR, 0 BTC, x ETH

4. The bot receives an order to go long on BTC-EUR;
  * Total balance = 50 EUR;
  * Pairs that are currently short:  BTC-EUR = 1;
  * EUR balance to purchase ETH: 50 EUR / 1 = 50 EUR;
5. The bot purchases 50 EUR worth of BTC.

Current balance: 0 EUR, y BTC, x ETH.
